#########################################
# author: ashraf minhaj
# email : ashraf_minhaj@yahoo.com
# 
# date: 08-12-23
# HushHub Frontend local dev environment
#########################################

version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
