#########################################
# author: ashraf minhaj
# email : ashraf_minhaj@yahoo.com
# 
# date: 02-12-23
# the HushHub frontend applicaion
# ** local development environment **
#########################################


FROM node:18 as builder
WORKDIR /app
    
COPY package*.json ./

RUN npm install

FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app/package*.json .
COPY --from=builder /app/node_modules ./node_modules

# copy and mount the node_modules dir 
# as volume otherwise it won't be found 
# by docker
VOLUME [ "/app/node_modules" ]
 
COPY . .

EXPOSE 3000

CMD ["npm", "start"]

# -----
# docker build -t front -f Dockerfile.dev .    
# docker run --rm -v .:/app -it -p 80:3000 --env-file .env front